version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  elasticsearch:
   container_name: elasticsearch
   hostname: elasticsearch
   image: elasticsearch:7.5.2
   volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
     - discovery.type=single-node
     - xpack.security.enabled=false
     - ES_JAVA_OPTS=-Xms512m -Xmx512m
   ports:
     - "9200:9200"
   networks:
     - event-manager
volumes:
  elasticsearch-data:
    driver: local
networks:
  event-market:
    driver: bridge

